version: 2

models:
  - name: fact_orders
    description: "Order fact table at the order header level"
    columns:
      - name: order_id
        description: "The primary key for the order fact table"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to the customer dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: order_date_id
        description: "Foreign key to the date dimension"
        tests:
          - not_null
      - name: order_status
        description: "Current order status"
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'processing', 'shipped', 'delivered', 'cancelled', 'returned']
      - name: total_amount
        description: "Total order amount"
        tests:
          - not_null
      - name: is_cancelled
        description: "Flag indicating if the order was cancelled"
      - name: is_delivered
        description: "Flag indicating if the order was delivered"
      - name: customer_previous_order_count
        description: "Number of previous orders by the customer at the time of this order"
      - name: created_at
        description: "Timestamp when order was created"
        tests:
          - not_null
      - name: updated_at
        description: "Timestamp when order was last updated"
      - name: _loaded_at
        description: "Timestamp when record was loaded"

  - name: fact_order_items
    description: "Order items fact table at the line item level"
    columns:
      - name: order_item_id
        description: "The primary key for the order items fact table"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to the order fact table"
        tests:
          - not_null
          - relationships:
              to: ref('fact_orders')
              field: order_id
      - name: product_id
        description: "Foreign key to the product dimension"
        tests:
          - not_null
      - name: customer_id
        description: "Foreign key to the customer dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: order_date_id
        description: "Foreign key to the date dimension"
        tests:
          - not_null
      - name: quantity
        description: "Quantity ordered"
        tests:
          - not_null
      - name: unit_price
        description: "Price at time of order"
        tests:
          - not_null
      - name: item_total
        description: "Total price for this line item (quantity * unit_price)"
        tests:
          - not_null
      - name: order_status
        description: "Current order status"
        tests:
          - not_null
      - name: is_item_cancelled
        description: "Flag indicating if the item was cancelled"
      - name: _loaded_at
        description: "Timestamp when record was loaded"

  - name: fact_website_events
    description: "Website events fact table at the event level"
    columns:
      - name: event_id
        description: "The primary key for the website events fact table"
        tests:
          - unique
          - not_null
      - name: session_id
        description: "Website session identifier"
        tests:
          - not_null
      - name: customer_id
        description: "Foreign key to the customer dimension (null for anonymous users)"
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: product_id
        description: "Foreign key to the product dimension (for product-related events)"
      - name: event_type
        description: "Type of website event"
        tests:
          - not_null
          - accepted_values:
              values: ['page_view', 'product_view', 'add_to_cart', 'remove_from_cart', 'checkout', 'purchase']
      - name: page_url
        description: "URL of the page where the event occurred"
        tests:
          - not_null
      - name: page_path
        description: "Path component of the page URL"
      - name: device_type
        description: "Type of device used"
      - name: is_purchase_event
        description: "Flag indicating if this is a purchase event"
      - name: is_add_to_cart_event
        description: "Flag indicating if this is an add-to-cart event"
      - name: event_timestamp
        description: "Timestamp when event occurred"
        tests:
          - not_null
      - name: _loaded_at
        description: "Timestamp when record was loaded"